name: Deploy Terraform 
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
#     - name: init
#       run: terraform init
      
    - name: terraform destroy
      run: terraform destroy --auto-approve

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply --auto-approve

    - name: Get EC2 Instance Public IP
      run: |
        public_ip=$(terraform output -raw instance_public_ip)
        echo "Public IP Address of EC2 Instance: $public_ip"
        
    - name: Get RDS Endpoint
      run: |
        db_hostname=$(terraform output -raw rds_endpoint)
        echo "Public IP Address of EC2 Instance: $db_hostname"

        
    
